language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
addons:
  code_climate:
    repo_token: 160fd7a30883182d28f45ff405f5113dc2c1067f

